# Generated by Django 5.0.6 on 2026-05-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_useraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                default="email", help_text="email | google", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
