# Generated by Django 5.0.6 on 2026-05-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserAddress",
        ),
    ]
