# Generated by Django 5.0.6 on 2026-05-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_delete_useraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("online", "Online"), ("cod", "Cash on Delivery")],
                db_index=True,
                default="online",
                max_length=20,
            ),
        ),
    ]
