# Generated by Django 5.0.6 on 2026-05-03 12:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_delete_useraddress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("razorpay_order_id", models.CharField(db_index=True, max_length=100)),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("razorpay_signature", models.CharField(blank=True, max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                    ),
                ),
                ("signature_verified", models.BooleanField(default=False)),
                ("amount_paise", models.PositiveIntegerField()),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["order"], name="payments_order_i_b32b33_idx"),
                    models.Index(
                        fields=["razorpay_order_id"], name="payments_razorpa_c67522_idx"
                    ),
                    models.Index(
                        fields=["razorpay_payment_id"],
                        name="payments_razorpa_c6ca42_idx",
                    ),
                    models.Index(fields=["status"], name="payments_status_d621e5_idx"),
                ],
            },
        ),
    ]
